{"name": "test_post_demo", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5.985986 < 3\n +  where 5.985986 = <built-in method total_seconds of datetime.timedelta object at 0x107890bd0>()\n +    where <built-in method total_seconds of datetime.timedelta object at 0x107890bd0> = datetime.timedelta(seconds=5, microseconds=985986).total_seconds\n +      where datetime.timedelta(seconds=5, microseconds=985986) = <Response [201]>.elapsed", "trace": "self = <tests.test_demo_data_driving.TestPytestDemo object at 0x106e3ee90>\n\n>   ???\nE   assert 5.985986 < 3\nE    +  where 5.985986 = <built-in method total_seconds of datetime.timedelta object at 0x107890bd0>()\nE    +    where <built-in method total_seconds of datetime.timedelta object at 0x107890bd0> = datetime.timedelta(seconds=5, microseconds=985986).total_seconds\nE    +      where datetime.timedelta(seconds=5, microseconds=985986) = <Response [201]>.elapsed\n\n/Users/jane/Documents/Code/Pytest/demo/pytest_api_test_001/tests/test_demo_data_driving.py:52: AssertionError"}, "start": 1754668231688, "stop": 1754668237676, "uuid": "796e4c88-fa3e-4735-b6d3-b71bf9349984", "historyId": "1072e2885073a77487fa949f8bbc242d", "testCaseId": "1072e2885073a77487fa949f8bbc242d", "fullName": "tests.test_demo_data_driving.TestPytestDemo#test_post_demo", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_demo_data_driving"}, {"name": "subSuite", "value": "TestPytestDemo"}, {"name": "host", "value": "jane-2.local"}, {"name": "thread", "value": "13570-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_demo_data_driving"}]}